[package]
name = "liquidation_engine"
version = "0.1.0"
description = "Persat Finance liquidation engine"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "liquidation_engine"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
custom-heap = []
custom-panic = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build", "price_oracle/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
persat-core = { workspace = true }
pyth-solana-receiver-sdk = { workspace = true }
price_oracle = { path = "../price_oracle", features = ["no-entrypoint"] }
