"use client";
import { useMemo, useState } from "react";
import { Button, Card, Input } from "@/lib/design-system";

export function TermsForm({ mode }: { mode: "private" | "public" }) {
  const [principal, setPrincipal] = useState(2000);
  const [rate, setRate] = useState(1500);
  const [duration, setDuration] = useState(6);
  const [loanMint, setLoanMint] = useState<"USDC" | "USDT">("USDC");
  const [counterparty, setCounterparty] = useState("");
  const summary = useMemo(() => ({ interest: principal * (rate / 10000) * (duration / 12), monthly: (principal * (1 + (rate / 10000) * (duration / 12))) / duration, collateralUsd: principal * 2 }), [principal, rate, duration]);
  return <div className="mt-10 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><Card><form className="space-y-6" onSubmit={(event) => event.preventDefault()}><div><label className="eyebrow block pb-2" htmlFor="principal">Loan amount ({loanMint})</label><Input id="principal" type="number" min="1" value={principal} onChange={(e) => setPrincipal(Math.max(1, Number(e.target.value)))} /></div><fieldset><legend className="eyebrow mb-3">Loan currency</legend><div className="grid grid-cols-2 gap-3">{(["USDC", "USDT"] as const).map((mint) => <button type="button" key={mint} onClick={() => setLoanMint(mint)} className={`min-h-12 border font-mono text-xs tracking-widest ${loanMint === mint ? "border-amber bg-amber/10 text-white" : "border-amber/20 bg-ink text-orange-50"}`}>{mint}</button>)}</div></fieldset><fieldset><legend className="eyebrow mb-3">Duration</legend><div className="grid grid-cols-3 gap-3">{[6, 12, 24].map((months) => <button type="button" key={months} onClick={() => setDuration(months)} className={`min-h-14 border font-mono text-xs ${duration === months ? "border-amber bg-amber/10 text-white" : "border-amber/20 bg-ink text-orange-50"}`}>{months} months</button>)}</div></fieldset><div><label className="eyebrow block pb-2" htmlFor="rate">Annual rate (basis points)</label><Input id="rate" type="number" min="1" max="100000" value={rate} onChange={(e) => setRate(Math.max(1, Number(e.target.value)))} /></div>{mode === "private" && <div><label className="eyebrow block pb-2" htmlFor="counterparty">Counterparty Solana wallet — optional</label><Input id="counterparty" value={counterparty} onChange={(e) => setCounterparty(e.target.value)} placeholder="Leave blank to generate a single-use link" /></div>}<p className="text-sm text-orange-50">Wallet signing and deal creation activate only after the secure Solana deployment configuration is complete.</p><Button className="w-full">{mode === "private" ? counterparty ? "Prepare direct deal" : "Generate private link" : "Post structured listing"}</Button></form></Card><Card><p className="eyebrow">Live terms summary</p><dl className="mt-6 space-y-4 font-mono text-sm"><Row label="Borrower receives" value={`${principal.toLocaleString()} ${loanMint}`} /><Row label="Estimated total interest" value={`${summary.interest.toFixed(2)} ${loanMint}`} /><Row label="Estimated monthly installment" value={`${summary.monthly.toFixed(2)} ${loanMint}`} /><Row label="Required collateral at 50% LTV" value={`$${summary.collateralUsd.toLocaleString()} BTC value`} /><Row label="Liquidation safety" value="Calculated from live BTC/USD only when a fresh oracle is available" /></dl></Card></div>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="border-b border-amber/10 pb-4"><dt className="text-[10px] uppercase tracking-widest text-orange-50/70">{label}</dt><dd className="mt-1 text-white">{value}</dd></div>; }
