[package]
name = "loan_lifecycle"
version = "0.1.0"
description = "Persat Finance loan lifecycle and payment program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "loan_lifecycle"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
custom-heap = []
custom-panic = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
persat-core = { workspace = true }
