[package]
name = "price_oracle"
version = "0.1.0"
description = "Persat Finance single BTC/USD price oracle adapter"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "price_oracle"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
custom-heap = []
custom-panic = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
persat-core = { workspace = true }
